// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_counts_for_candidate_core
List cpp_counts_for_candidate_core(IntegerVector idx_treatment, IntegerVector idx_control, IntegerVector order_vec, NumericVector weights, NumericVector thresholds_by_endpoint, IntegerVector type_code, NumericMatrix time_mat, IntegerMatrix event_mat, NumericMatrix value_mat, NumericMatrix followup_mat, List recurrent_times, List recurrent_start, List recurrent_len);
RcppExport SEXP _MaxWin_cpp_counts_for_candidate_core(SEXP idx_treatmentSEXP, SEXP idx_controlSEXP, SEXP order_vecSEXP, SEXP weightsSEXP, SEXP thresholds_by_endpointSEXP, SEXP type_codeSEXP, SEXP time_matSEXP, SEXP event_matSEXP, SEXP value_matSEXP, SEXP followup_matSEXP, SEXP recurrent_timesSEXP, SEXP recurrent_startSEXP, SEXP recurrent_lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type idx_treatment(idx_treatmentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx_control(idx_controlSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type order_vec(order_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thresholds_by_endpoint(thresholds_by_endpointSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type type_code(type_codeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type time_mat(time_matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type event_mat(event_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type value_mat(value_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type followup_mat(followup_matSEXP);
    Rcpp::traits::input_parameter< List >::type recurrent_times(recurrent_timesSEXP);
    Rcpp::traits::input_parameter< List >::type recurrent_start(recurrent_startSEXP);
    Rcpp::traits::input_parameter< List >::type recurrent_len(recurrent_lenSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_counts_for_candidate_core(idx_treatment, idx_control, order_vec, weights, thresholds_by_endpoint, type_code, time_mat, event_mat, value_mat, followup_mat, recurrent_times, recurrent_start, recurrent_len));
    return rcpp_result_gen;
END_RCPP
}
// cpp_two_endpoint_base_counts
List cpp_two_endpoint_base_counts(NumericVector futime, IntegerVector cnsr, IntegerVector arm, NumericVector hosp_times, IntegerVector hosp_start, IntegerVector hosp_len);
RcppExport SEXP _MaxWin_cpp_two_endpoint_base_counts(SEXP futimeSEXP, SEXP cnsrSEXP, SEXP armSEXP, SEXP hosp_timesSEXP, SEXP hosp_startSEXP, SEXP hosp_lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type futime(futimeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cnsr(cnsrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type arm(armSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hosp_times(hosp_timesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hosp_start(hosp_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hosp_len(hosp_lenSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_two_endpoint_base_counts(futime, cnsr, arm, hosp_times, hosp_start, hosp_len));
    return rcpp_result_gen;
END_RCPP
}
// cpp_two_endpoint_threshold_counts
List cpp_two_endpoint_threshold_counts(NumericVector futime, IntegerVector cnsr, IntegerVector arm, NumericVector hosp_times, IntegerVector hosp_start, IntegerVector hosp_len, NumericVector t_grid);
RcppExport SEXP _MaxWin_cpp_two_endpoint_threshold_counts(SEXP futimeSEXP, SEXP cnsrSEXP, SEXP armSEXP, SEXP hosp_timesSEXP, SEXP hosp_startSEXP, SEXP hosp_lenSEXP, SEXP t_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type futime(futimeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cnsr(cnsrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type arm(armSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hosp_times(hosp_timesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hosp_start(hosp_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hosp_len(hosp_lenSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t_grid(t_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_two_endpoint_threshold_counts(futime, cnsr, arm, hosp_times, hosp_start, hosp_len, t_grid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MaxWin_cpp_counts_for_candidate_core", (DL_FUNC) &_MaxWin_cpp_counts_for_candidate_core, 13},
    {"_MaxWin_cpp_two_endpoint_base_counts", (DL_FUNC) &_MaxWin_cpp_two_endpoint_base_counts, 6},
    {"_MaxWin_cpp_two_endpoint_threshold_counts", (DL_FUNC) &_MaxWin_cpp_two_endpoint_threshold_counts, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_MaxWin(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
