# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_counts_for_candidate_core <- function(idx_treatment, idx_control, order_vec, weights, thresholds_by_endpoint, type_code, time_mat, event_mat, value_mat, followup_mat, recurrent_times, recurrent_start, recurrent_len) {
    .Call(`_MaxWin_cpp_counts_for_candidate_core`, idx_treatment, idx_control, order_vec, weights, thresholds_by_endpoint, type_code, time_mat, event_mat, value_mat, followup_mat, recurrent_times, recurrent_start, recurrent_len)
}

cpp_two_endpoint_base_counts <- function(futime, cnsr, arm, hosp_times, hosp_start, hosp_len) {
    .Call(`_MaxWin_cpp_two_endpoint_base_counts`, futime, cnsr, arm, hosp_times, hosp_start, hosp_len)
}

cpp_two_endpoint_threshold_counts <- function(futime, cnsr, arm, hosp_times, hosp_start, hosp_len, t_grid) {
    .Call(`_MaxWin_cpp_two_endpoint_threshold_counts`, futime, cnsr, arm, hosp_times, hosp_start, hosp_len, t_grid)
}

